### ISSUE TITLE
PostgreSQL timeouts

### ISSUE THREAD

**Issue by vergilet** [ankane/slowpoke#15]
Hi @ankane,
So, is it possible to catch the db timeout with gem? Using Heroku.
I've added 
```yml
production:
  variables:
    statement_timeout: <%= Slowpoke.timeout * 1000 %>
```

And initializator has
```ruby
Slowpoke.timeout = 29
``` 

But application raises 500 (instead of 503) with `PG::QueryCanceled: ERROR:  canceling statement due to statement timeout`

Any suggestions?
Thanks!
