### ISSUE TITLE
rake db:migrate does not use the correct timeout

### ISSUE THREAD

**Issue by zhaohanweng** [ankane/slowpoke#6]
I am using rails 4.1, in my `database.yml`

```
development:
  adapter: postgresql
  encoding: unicode
  database: socialsift_development
  pool: 25
  variables:
    statement_timeout: 3000
```

When I run a migration longer than 3 s, it will fail due to statement_timeout. Even if I set `MIGRATION_STATEMENT_TIMEOUT=0` in my env, it still fails after 3 second.
